...

diff --git a/bin/cpg b/bin/cpg
--- a/bin/cpg
+++ b/bin/cpg
@@ -1,7 +1,28 @@
 #!/bin/zsh
 
+# Initialize variables
+debug_mode=0
+file_name=""
+
+# Parse command line arguments
+while getopts ":d" opt; do
+  case $opt in
+    d)
+      debug_mode=1
+      ;;
+    \?)
+      echo "Invalid option: -$OPTARG" >&2
+      exit 1
+      ;;
+  esac
+done
+
+# Shift the options so that $1 becomes the file name
+shift $((OPTIND-1))
+
 if [ $# -eq 0 ]; then
     echo "Error: No file name provided."
+    echo "Usage: $0 [-d] <filename>"
     exit 1
 fi
 
@@ -9,7 +30,13 @@ file_name=$1
 
 if [ -f "$file_name" ]; then
     echo "Compiling $file_name"
-    g++ -std=c++11 -O2 -Wall "$file_name" -o "cpg.out"
+    
+    if [ $debug_mode -eq 1 ]; then
+        g++ -DDEBUG_PRINT -std=c++11 -O2 -Wall -Wextra -Wshadow -pedantic -D_GLIBCXX_DEBUG -D_GLIBCXX_DEBUG_PEDANTIC "$file_name" -o "cpg.out"
+    else
+        g++ -std=c++11 -O2 -Wall -Wextra -Wshadow -pedantic -D_GLIBCXX_DEBUG -D_GLIBCXX_DEBUG_PEDANTIC "$file_name" -o "cpg.out"
+    fi
+    
     if [ $? -eq 0 ]; then
         if [ -f "./input" ]; then
             echo "Found input file."
@@ -27,4 +54,3 @@ if [ -f "$file_name" ]; then
 else
     echo "Error: C++ file not found."
 fi
-
